#thymeleaf start
spring:
  thymeleaf:
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
#开发时关闭缓存,不然没法看到实时页面
      cache: false
#thymeleaf end
  datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
      properties:
          hibernate:
              hbm2ddl:
                  auto: create-drop
#时间格式化
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss

#时区设置
      time-zone: Asia/Chongqing

# 应用自定义配置

  redis:
      database: 0
      host: localhost
      port: 6379
      password:
      pool:
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 0
logging:
  config: classpath:logback_first.xml

